Hw03
andrii-pozniak/nodejs-homework-rest-api pull request #2
Opened 2023-01-25 19:47 UTC by andrii-pozniak

2023-01-25 19:50 UTC, andrii-pozniak commented
Check out my work, please.

2023-01-26 15:00 UTC, Eastvarga requested changes
Відсутній окремий єндпоінт для апдейту, уважно читайте завдання

2023-01-26 15:00 UTC, Eastvarga commented on models/contact.js
> +        .email({ minDomainSegments: 2, tlds: { allow: ['com', 'net'] } }),
чому пошта не є .required()??

2023-01-26 15:00 UTC, Eastvarga commented on models/contact.js
> +const addSchema = Joi.object({
Схеми БД та схеми валідаціїї це різні схеми, вони не повинні знаходитись у одному модулі

2023-01-26 15:00 UTC, Eastvarga commented on routes/api/contacts.js
> +    return res.json({ contacts });
res.json( contacts );  так набагато краще - повернеться масив контактів без зайвої вкладеності у поле contacts

2023-01-26 15:00 UTC, Eastvarga commented on routes/api/contacts.js
return res.json({
      status: "success",
      code: 200,
      data: {
        data: result
      }
    }); Вам вже не потрібна ця конструкція. Повинні вже зрозуміти що у тілі відповіді має бути необхідна та достатня інформація
     return res.status(200).json(result); - цього достатньо

2023-01-26 15:00 UTC, Eastvarga commented on routes/api/contacts.js
> +    const { error } = schemas.addSchema.validate(req.body);
Треба винести валідацію у окремий мідлвар

2023-01-26 15:00 UTC, Eastvarga commented on routes/api/contacts.js
>        status: "success",
знову зайва інформація у тілі відповіді, краще
res.status(201).json(result);

2023-01-26 15:00 UTC, Eastvarga commented on routes/api/contacts.js
> +    const { error } = schemas.addSchema.validate(req.body);
Винести треба валідацію у мідлвар

2023-01-26 15:00 UTC, Eastvarga commented on server.js
> +const { DB_HOST, PORT = 3000 } = process.env;
це добре, але спробуйте ці змінні винести у файл окремий валідації та вже там ініціалізувати їх та імпортувати туди де потрібно

2023-01-26 15:00 UTC, Eastvarga commented on server.js
> +mongoose.connect(DB_HOST)
добре, але можна і async await спробувати щоб непромісом базу конектити а потім сервер запустити

2023-01-28 08:25 UTC, andrii-pozniak commented on models/contact.js
> +        .email({ minDomainSegments: 2, tlds: { allow: ['com', 'net'] } }),
виправив

2023-01-28 08:25 UTC, andrii-pozniak commented on models/contact.js
> +const addSchema = Joi.object({
виправив

2023-01-28 08:33 UTC, andrii-pozniak commented on routes/api/contacts.js
виправив

2023-01-29 11:10 UTC, Eastvarga requested changes
Попередні зауваження не усунені, чому?
відсутній ендпоінт апдейту поля favorite

2023-01-29 11:10 UTC, Eastvarga commented on middleware/validationContactSchemaJoi.js
> +                .email({ minDomainSegments: 2, tlds: { allow: ['com', 'net'] } }),
Пошта так і не виправлена, будьте уважні - поле повинно бути  .required(),

2023-01-29 15:04 UTC, andrii-pozniak commented on routes/api/contacts.js
> +    const { error } = schemas.addSchema.validate(req.body);
виправив

2023-01-29 15:04 UTC, andrii-pozniak commented on routes/api/contacts.js
>        status: "success",
вивправив

2023-01-29 15:05 UTC, andrii-pozniak commented on server.js
> +mongoose.connect(DB_HOST)
??

2023-01-29 15:05 UTC, andrii-pozniak commented on middleware/validationContactSchemaJoi.js
> +                .email({ minDomainSegments: 2, tlds: { allow: ['com', 'net'] } }),
виправив

2023-01-29 17:10 UTC, Eastvarga requested changes
Є помилки

2023-01-29 17:10 UTC, Eastvarga commented on routes/api/contacts.js
> +router.patch('/:contactId/favorite', addValidationFavorite, ctrlConstants.getById);
не вірний контроллер  ctrlConstants.getById для апдейту  - будьте уважні, та перевіряйте свій код.
addValidationFavorite - краще ім'я validateToggleFavorite - ім'я повинно відображати функціонал -те що робіть функція

2023-01-30 16:12 UTC, Eastvarga approved these changes

2023-01-30 16:13 UTC, merged