all homework4
andrii-pozniak/nodejs-homework-rest-api pull request #3
Opened 2023-02-05 16:03 UTC by andrii-pozniak

2023-02-05 17:37 UTC, Eastvarga requested changes
Є зауваження

2023-02-05 17:37 UTC, Eastvarga commented on app.js
> +app.use("/api/users", routerCurrent)
а чому окремо зробили раут? не дуже добре, але й так зійде

2023-02-05 17:37 UTC, Eastvarga commented on controllers/signup.js
> +        res.status(201).json(result)
пароль ніколи не віддається на любий запит, навіть хеш паролю

2023-02-05 17:37 UTC, Eastvarga commented on middleware/auth.js
> +        };
перевірте token також, він не повинен бути пустим

2023-02-05 17:37 UTC, Eastvarga commented on middleware/validationUserSchema.js
> +        email: Joi.string()
пошта теж обов'язкове поле повинно бути

2023-02-05 17:37 UTC, Eastvarga commented on routes/api/contacts.js
>  router.get('/:contactId', ctrlConstants.getById);
для усіх раутів контактів потрібен мідлвар auth

2023-02-05 18:49 UTC, andrii-pozniak commented on app.js
> +app.use("/api/users", routerCurrent)
виправив

2023-02-05 18:49 UTC, andrii-pozniak commented on controllers/signup.js
> +        res.status(201).json(result)
виправив

2023-02-05 18:53 UTC, andrii-pozniak commented on middleware/auth.js
> +        };
На 20 перевіряеться
if (!user || !user.token) {
            return res.status(401).json({
                message: "Not authorized"
            });

2023-02-05 18:56 UTC, andrii-pozniak commented on routes/api/contacts.js
>  router.get('/:contactId', ctrlConstants.getById);
виправив

2023-02-06 16:46 UTC, Eastvarga commented on middleware/auth.js
> +        };
Не плутайте, перевірку того, чи прийшов до вас не пустий токен, та токо чи є токен у юзера.
До того ж токен що у юзера повинен співпадати з токеном котрий прийшов у запиті

2023-02-06 16:54 UTC, Eastvarga requested changes
Э маленьке зауваження.

2023-02-06 16:54 UTC, Eastvarga commented on middleware/auth.js
> +        if (!user || !user.token) {
тут має бути перевірка токена 
 if (!user || user.token!==token)

2023-02-06 19:18 UTC, Eastvarga approved these changes

2023-02-06 19:18 UTC, merged