resolved homework5
andrii-pozniak/nodejs-homework-rest-api pull request #4
Opened 2023-02-14 17:55 UTC by andrii-pozniak

2023-02-14 18:29 UTC, Eastvarga requested changes
Є зауваження

2023-02-14 18:29 UTC, Eastvarga commented on controllers/signup.js
> +        console.log(result)
ніяких консолей

2023-02-14 18:29 UTC, Eastvarga commented on controllers/signup.js
> +        const avatarURL = path.join("public", "avatars", imageName);
невірно, як з цього запису вийде подібне до цього
**http://locahost:<порт>/avatars/<ім'я файлу з розширенням>** ??

2023-02-14 18:29 UTC, Eastvarga commented on routes/api/users.js
> +router.patch("/avatars", auth, upload.single("avatar"), ctrlUsers.updateAvatar);
А де саме підключення статичної теки public?

2023-02-14 20:10 UTC, andrii-pozniak commented on controllers/signup.js
> +        console.log(result)
виправив

2023-02-14 20:10 UTC, andrii-pozniak commented on controllers/signup.js
> +        const avatarURL = path.join("public", "avatars", imageName);
Змінив

2023-02-14 20:13 UTC, andrii-pozniak commented on routes/api/users.js
> +router.patch("/avatars", auth, upload.single("avatar"), ctrlUsers.updateAvatar);
Змінив

2023-02-15 18:09 UTC, Eastvarga approved these changes

2023-02-15 18:09 UTC, Eastvarga commented on controllers/signup.js
> +        const avatarURL = path.join( "/avatars", imageName);
Абсолютно у всіх фатальне нерозуміння того що є URL шлях, а що є шлях файлової системи. 
URL= HOST(http://localhost:3000) +"/" +"avatars"+"/"+imageName
path = __dirname(C:\somedir\...\root)+"\"+"avatars"+"\"+imageName
Невже важко знайти інформацію у інтернеті
https://uk.wikipedia.org/wiki/%D0%A3%D0%BD%D1%96%D1%84%D1%96%D0%BA%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B9_%D0%BB%D0%BE%D0%BA%D0%B0%D1%82%D0%BE%D1%80_%D1%80%D0%B5%D1%81%D1%83%D1%80%D1%81%D1%96%D0%B2
https://uk.wikipedia.org/wiki/%D0%A8%D0%BB%D1%8F%D1%85_%D1%84%D0%B0%D0%B9%D0%BB%D1%83

2023-02-15 18:09 UTC, merged